on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: erlang:25-alpine
    name: Lint
    steps:
      - uses: actions/checkout@v3
      - run: rebar3 fmt -c
  test:
    strategy:
      matrix:
        otp-version: [23, 24, 25]
    runs-on: ubuntu-latest
    container:
      image: erlang:${{matrix.otp-version}}-alpine
    name: OTP ${{matrix.otp-version}}
    steps:
      - uses: actions/checkout@v3
      - run: rebar3 eunit
